[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production"

# Ignore Python files during build
[build.ignore]
  requirements = "requirements.txt"
  python_setup = "setup.py"
  pyproject = "pyproject.toml"

# Ensure only Next.js build runs
[[plugins]]
  package = "@netlify/plugin-nextjs" 