[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Use Next.js plugin for proper API route handling
[[plugins]]
  package = "@netlify/plugin-nextjs" 